<a href="https://colab.research.google.com/github/samiha-mahin/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a.ndim)

2


In [ ]:
print(a.itemsize)

8


In [ ]:
print(a.shape)

(3, 3)


In [ ]:
b =  np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
b.dtype

dtype('float64')

In [ ]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#array fillers
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c = np.full ((4,5),30)
c

array([[30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30]])

In [ ]:
c = np.linspace(1,5,50) # 50 data from 1 to 5
c

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
x = np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#math operation
a = np.arange(2,22).reshape(4,5)
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [ ]:
a.min()

2

In [29]:
a = np.arange(2,22).reshape(4,5)
a.sum(axis=0)

array([38, 42, 46, 50, 54])

In [ ]:
a.sum(axis=1)

array([20, 45, 70, 95])

In [ ]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569]])

In [ ]:
b = np.arange(0,30).reshape(3,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
#slicing
b[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
b[0:2]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [3]:
import numpy as np
b = np.arange(0,30).reshape(3,10)
b[:,4:] #array values from 4th index to last

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [5]:
#looping
#looping
import numpy as np
a = np.arange(6,12).reshape(3,2)
for row in a:
  print (row)

[6 7]
[8 9]
[10 11]


In [6]:
for row in a.flat:
  print (row)

6
7
8
9
10
11


In [8]:
a = np.arange(0,12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)


In [9]:
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [10]:
a*b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [7]:
a = np.arange(6,12).reshape(3,2)
b = np.arange(12,18).reshape(3,2)
np.vstack((a,b))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [11]:
np.hstack((a,b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [13]:
np.hsplit(a,1)


[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [14]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [23]:
b = (a < 5)


In [30]:
a = np.arange(6,12).reshape(3,2)
b = np.arange(0,6).reshape(3,2)


In [31]:
for x,y in np.nditer([a,b]):
  print (x,y)

6 0
7 1
8 2
9 3
10 4
11 5
